apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "82258894-ingress"
spec:
  ingressClassName: nginx
  rules:
  - host: "*.ce-82258894-sa"
    http:
      paths:
      - path: /
        backend:
          service:
            name: my-82258894
            port:
              number: 8080
        pathType: Prefix
